cart/urls.py
from django.conf.urls import url
from django.urls import  path
from . import views

app_name = 'cart'

urlpatterns = [
    path('yourcart', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path("cart_size/",views.cart_size, name="cart_size"),

]

orders/urls.py
from django.urls import  path
from . import views

app_name = 'orders'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('checkout_success/',views.checkout_success,name='checkout_success'),
    path('checkout_fail/',views.checkout_fail,name='checkout_fail'),
    path('checkout_payment/<str:order_number>/',views.checkout_payment,name='make_payment'),

    path("orders/",views.orders,name="orders"),
    path('order_items/<str:order_number>/<int:pk>/',views.order_items,name='order_items'),
    path('my_orders/',views.my_order_detail,name='my_order_detail'),

    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # <-- this one here


]

solvergeek/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    # path('ecommerce/',include('ecommerce.urls')),
    path('', include('ecommerce.urls')),
    path('xconnect/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('orders.urls')),
    path('', include('cart.urls')),
    path('', include('reports.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('terms_and_conditions/', TemplateView.as_view(
        template_name='terms_and_conditions.html'), name='termsandconditions'),
    path('return_policy/', TemplateView.as_view(template_name='return_policy.html'),
         name='returnpolicy'),


]#+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
elif getattr(settings, 'FORCE_SERVE_STATIC', False):
    settings.DEBUG = True
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    settings.DEBUG = False

# urlpatterns+=static(settings.MEDIA_ROOT,document_root=settings.MEDIA_ROOT)

# handler404 = 'ecommerce.views.error404'
# handler500 = 'ecommerce.views.error500'

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 101)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from ecommerce.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from  django.http import  HttpResponse,JsonResponse


@require_POST
def cart_add(request,product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(Product, id=product_id) 
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
        # print("cart_total",len(cart))
    # return HttpResponse()
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request,'cart/cart_detail.html', {'cart': cart})


def cart_size(request):
    cart = Cart(request)
    return JsonResponse({'size': len(cart)})

templates/cart/cart_detail.html
{% extends 'header1.html' %}

{% load static %}
{% load humanize %}
{% load thumbnail %}
{% block title %}

Your Shopping Cart
{% endblock %}


{% block content %}

<!-- start -->
<div class="container">
<div class="row">
    <div class="col">
        <div class="order-summary clearfix">
           
                <h3 class="title section-title">Cart Review</h3>

                
            
            <table class="shopping-cart-tablve table">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th class="text-center">Price</th>
                        <th class="text-center">Quantity</th>
                        <th class="">Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart %}
                    {% with product=item.product  %}
                    <tr>
                        <td class="">
                            <a href="{{product.get_absolute_url}}">
                                
                                <img class="img-responsive" src="{{ product.image.url }}" alt="{{ product.image.url }}"style="height:100px; width:100px">
                            </a>
                            <a href="{{product.get_absolute_url}}" style="color:#FA7A62;">{{product.name|truncatewords:20}}</a>

                        </td>

                        
                        <td class="price text-center"><strong>GH₵ {{product.percentageoff|intcomma}}</strong><br><del
                                class="font-weak"><small>
                                  
                                 
                                </small></del></td>

                        <td class="qty text-center">
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {% csrf_token %}
                                <p> {{ item.update_quantity_form.quantity }}</p>
                                <p> {{ item.update_quantity_form.update }}</p>
                                
                                <input type="submit" value="Update" class="btn">
                            </form>
                        </td>
                        <td class="">
                            <a class="main-btn text-danger" href="{% url "cart:cart_remove" product.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                    </td>
                    </tr>

                    {% endwith %}
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>SUBTOTAL</th>
                        <th colspan="2" class="sub-total">GH₵ {{ cart.get_total_price|intcomma }}</th>
                    </tr>
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>SHIPING</th>
                        <td colspan="2">Free Shipping</td>
                    </tr>
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>TOTAL</th>
                        <th colspan="2" class="total">
                            {% with totail_items=cart|length %}
                            {% if cart|length > 0 %}
                            GH₵ {{ cart.get_total_price|intcomma }}
                            {% else %}
                            Your cart is empty.
                            {% endif %}
                            {% endwith %}
                        </th>
                    </tr>
                </tfoot>
            
            </table>


           
        </div>
       
    </div>
    
</div>
<ul class="ul" style="background-color: #3D589E; color: white">
    
    </li class="li">
        <a class="btn btn-outline-default" style="color: white" href="/">Continue Shopping</a>
       
    </li>
    </li>
    <li class="li">

        {% if cart.get_total_price > 1 %}
        <a style="color: white" href="{% url 'orders:checkout' %}" class="btn btn-outline-default">Checkout</a>

        {% endif %}
    </li>
</ul>
</div>

<style>
  
    .li{
        display: inline;
    
    }
    .ul{
        text-align: center;
        background-color: #4654A3;
    }
</style>
{% endblock %}