cart/urls.py
from django.conf.urls import url
from django.urls import  path
from . import views

app_name = 'cart'

urlpatterns = [
    path('yourcart', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path("cart_size/",views.cart_size, name="cart_size"),

]

reports/urls.py
from django.urls import  path
from . import views

app_name = 'reports'
urlpatterns = [
    path('customers/',views.customers_data,name='customers'),
    path('customers_order_detail/<int:id>/',views.customers_order_detail,name='customers_order'),
    path('product_report/',views.product_report,name='product_report'),
    path('products_report_detail/<str:name>/',views.products_report_detail,name='products_report_detail'),
    path('products_remaiaining_detail/<str:name>/',views.products_remaiaining_detail,name='products_remaiaining_detail'),
    path('change_order_status/',views.change_order_status,name='change_order_status'),

]

solvergeek/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    # path('ecommerce/',include('ecommerce.urls')),
    path('', include('ecommerce.urls')),
    path('xconnect/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('orders.urls')),
    path('', include('cart.urls')),
    path('', include('reports.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('terms_and_conditions/', TemplateView.as_view(
        template_name='terms_and_conditions.html'), name='termsandconditions'),
    path('return_policy/', TemplateView.as_view(template_name='return_policy.html'),
         name='returnpolicy'),


]#+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
elif getattr(settings, 'FORCE_SERVE_STATIC', False):
    settings.DEBUG = True
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    settings.DEBUG = False

# urlpatterns+=static(settings.MEDIA_ROOT,document_root=settings.MEDIA_ROOT)

# handler404 = 'ecommerce.views.error404'
# handler500 = 'ecommerce.views.error500'

orders/models.py
import datetime

from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import F, Sum
from django.db.models.signals import post_save
from django.dispatch import receiver
from ecommerce.models import Base_Model, Product
from hashids import Hashids
from mapbox_location_field.models import LocationField
# from mapbox_location_field.spatial.models import SpatialLocationField  
from location_field.models.plain import PlainLocationField
# Create your models here.
hashids = Hashids()
from random import randint


class Staff_Email(Base_Model):
    
    name = models.ForeignKey(User,on_delete=models.CASCADE,limit_choices_to={'is_staff': True})
    email = models.EmailField()
    receive_order = models.BooleanField(default=True)
 


    class Meta:
        verbose_name = 'staff Email'
        verbose_name_plural='staff Emails'
    
    def __str__(self):
        return f'{self.name.username,self.email}'

class Region(Base_Model):
    name = models.CharField(max_length=200,unique=True)
    def __str__(self):
        return self.name

    class  Meta:
        ordering = ['name']

class City(Base_Model):
    region=models.ForeignKey(Region,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=200)

  

    def __str__(self):
        return f"{self.name} in {self.region}"
    
    class Meta:
        verbose_name = 'City'
        verbose_name_plural= 'Cities'
        ordering = ['name']


class Delevery_Status(Base_Model):
    name = models.CharField(max_length=600,default='Order Placed')

    class Meta:
        verbose_name = "Delevery Status"
        verbose_name_plural ='Delevery Status'
    
    def __str__(self):
        return self.name


class Pickupstation(Base_Model):
    name = models.CharField(max_length=600)

class Order(Base_Model):
    user =models.ForeignKey(User,on_delete=models.CASCADE,related_name='user')
    name = models.CharField(max_length=8000)
    email = models.EmailField()
    address = models.TextField(null=True)
    phone_number = models.CharField(max_length=15, blank=False)
    delevery_Status = models.ForeignKey(Delevery_Status,on_delete=models.CASCADE,null=True,blank=True)
    # city = models.CharField('City/Closest Landmark',max_length=600)
    
    region =models.ForeignKey(Region,on_delete=models.CASCADE,null=True,blank=True)
    city =models.ForeignKey(City,null=True,on_delete=models.CASCADE,blank=True)
    paid = models.BooleanField(default=False)
    order_number = models.CharField('order number',max_length=500,editable=False)
    location = LocationField(null=True,blank=True)  
    payment_method =models.CharField(max_length=255,null=True,blank=True,editable=False)

    city1 = models.CharField(max_length=255,null=True,blank=True)
    location_google = PlainLocationField(based_fields=['city1'], zoom=7,null=True,blank=True)
    transaction_id =models.CharField(max_length=200,null=True,blank=True)
    pickupstation = models.ForeignKey(Pickupstation,on_delete=models.CASCADE,blank=True,null=True)
    




    class Meta:
        ordering = ('-date_updated', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
    
        return sum(item.get_cost() for item in self.items.all())
    def __str__(self):
        return f'user: {self.user.username} order umber : {self.order_number}'
    
    def gettotal_oders(self):
        # print(len(self.order_number))
        return len(self.order_number)
    




def random_with_N_digits(n):
    range_start = 10**(n-1)
    range_end = (10**n)-1
    return randint(range_start, range_end)

# print (random_with_N_digits(2))

@receiver(post_save,sender=Order)
def create_orders_number(sender,instance,created,*args, **kwargs):
    # now = datetime.datetime.now().strftime("%Y%m%d%H%M")
    if not instance.order_number:
        
        # order_id = hashids.encrypt(instance.id)
        ordernummber= str(random_with_N_digits(8))#+''+str(order_id)
        instance.order_number = ordernummber
        instance.save()

    # print('ordernummber ',ordernummber)



class OrderItem(Base_Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.order.name)

    def get_cost(self):
        if self.price and self.quantity:
            
            return self.price * self.quantity
        else:
            return None


    def grand_total(self):
        return self.get_cost
      



@receiver(post_save,sender=OrderItem)
def subtract_stock(sender,instance,created,*args, **kwargs):
    if created:
        # print('instance signal',instance.product.name,'quantity',instance.quantity)

        products = Product.objects.filter(name=instance.product.name).update(
            quantity=F('quantity')-instance.quantity)
        
    if  instance.product.quantity <=0:
        print('instance signal',instance.product.name,'quantity',instance.product.quantity)

reports/models.py
from django.db import models

# Create your models here.

reports/forms.py
from django import forms
from orders.models import Order


class DeleveryStatusForm(forms.ModelForm):

    class Meta:

        model = Order
        fields = ['delevery_Status',]

reports/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import user_passes_test
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User
from orders.models import Order, OrderItem, Delevery_Status
from ecommerce.models import Sub_Category, Product
from django.contrib.auth.decorators import login_required
from .forms import DeleveryStatusForm
from django.contrib import messages
from django.db.models import Sum, Count, Max
# Create your views here.


# @user_passes_test(lambda u: u.is_staff)
# @staff_member_required
def customers_data(request):
    if not request.user.is_staff:
        return redirect('/')
    # customers = User.objects.filter(is_staff=False,is_superuser=False)
    orders = Order.objects.values('user__username', 'user__email', 'user__id', 'user__date_joined', 'user__last_login').filter(user__is_staff=False, user__is_superuser=False)\
        .annotate(orders_total=Count('order_number', distinct=True), purchase=Count('items', distinct=True)).order_by('user__username')

    q1 = request.GET.get('q1')
    q2 = request.GET.get('q2')
    if q1 or q2:

        orders = orders.filter(date_updated__date__range=[q1, q2]).order_by('-order_number')\
            .annotate(orders_total=Count('order_number', distinct=True), purchase=Count('items', distinct=True)).order_by('user__username')

        # print(orders.query)

    context = {
        # 'customers':customers,
        "orders": orders,

    }
    return render(request, 'reports/customers.html', context)


@login_required
def customers_order_detail(request, id):
    orders = Order.objects.filter(user__id=id)

    order_size = orders.aggregate(orders_size=Count('items'))

    print(order_size)
    context = {
        'orders': orders,
        'user': User.objects.get(id=id),
        'order_size': order_size,
    }

    return render(request, 'reports/customer_orders.html', context)


def product_report(request):
    mostly_bought_products = Sub_Category.objects.values('name')\
        .annotate(quantity_available=Sum('products__quantity'))  # ,quantity_bought=Sum('products__order_items__quantity'))

    # print(mostly_bought_products.query)
    quantity_sold_products = Sub_Category.objects.values('name')\
        .annotate(quantity_bought=Sum('products__order_items__quantity'))

    out_of_stock = Product.objects.filter(quantity__lte=20).values(
        'category__name', 'quantity', 'name').order_by('-quantity')

    context = {
        'mostly_bought_products': mostly_bought_products,
        'quantity_sold_products': quantity_sold_products,
        "out_of_stock": out_of_stock,
    }
    return render(request, 'reports/products_report.html', context)


def products_report_detail(request, name):
    Product_available = Product.objects.filter(category__name=name)

    context = {
        "Product_available": Product_available,
        'name': name,
    }

    return render(request, 'reports/product_report_detail.html', context)


def products_remaiaining_detail(request, name):
    Product_sold_out = OrderItem.objects.filter(
        product__category__name=name).order_by('-date_updated', '-quantity')

    q1 = request.GET.get('q1')
    q2 = request.GET.get('q2')
    if q1 or q2:
        Product_sold_out = Product_sold_out.filter(
            date_updated__date__range=[q1, q2])

    Product_sold_out_summary = Product_sold_out.values('product__name').annotate(
        total_quantity=Sum('quantity')).order_by('product__name')
    # print(Product_sold_out_summary.query)

    context = {
        "Product_sold_out": Product_sold_out,
        'name': name,
        "sold_size": Product_sold_out.count(),
        'Product_sold_out_summary': Product_sold_out_summary,
        'Product_sold_out_summary_size': Product_sold_out_summary.aggregate(orders_size=Sum('total_quantity')),

    }

    return render(request, 'reports/products_remaiaining_detail.html', context)


def change_order_status(request):
    form = DeleveryStatusForm()
    q = request.GET.get('q')
    orders = Order.objects.all()
   

    # delivery_status = Delevery_Status.objects.only('name')
    try:
        if q:
            orders = orders.filter(order_number__icontains=q)
            order_number = orders.get(order_number__iexact=q)
            order_number = order_number.order_number
            # customer_name =order_number.user.get_full_name()

        if request.method == 'POST':
            delevery_Status = request.POST.get('delevery_Status')

            # print("delevery_Status", delevery_Status)
            orders = orders = orders.get(order_number=order_number)
            orders.delevery_Status_id = delevery_Status
            orders.save()
            # print('orders', orders.delevery_Status)
            messages.success(request,'order status updated')
            return redirect('reports:customers')
    except Order.DoesNotExist:
        pass

    context = {
        'orders': orders,
        'clear_content': True,
        # "customer_name":order_number.user,
        "form": form,
        "order_size": orders.aggregate(orders_size=Count('items')),
    }

    return render(request, 'reports/customer_orders.html', context)

templates/reports/customer_orders.html
{% extends 'header1.html' %}
{% load static %}

{% block content %}


<div class="container">
    <form action="{% url 'reports:change_order_status' %}" method="get">
        <div class="input-group text-center" style="justify-content:center">
            <input class="form-control" type="search" name="q" value="{{request.GET.q}}" placeholder="search for order number or code" required>
            <button class="btn btn-search " style="background-color: black;color: white;"
            type="submit">search</button>
        </div>
    </form>
    <div class="row">
       
        <div class="col">
           
           
            <a class="btn" style="background-color: #3d589e; color: white" href="{% url 'reports:customers' %}"> Back</a>
            <span class="btn badge badge-primary float-right display-4"  style="background-color: #3d589e; color: white" >Total {{order_size.orders_size}}</span>
           
            
            <h4 class="text-center uppercase"> ORDER INFO </h4> 
          
          


            {% for orders_placeed in orders %}


            <ul class="table table-striped">
                <li>Name {{orders_placeed.name}}</li>
                <li>Order Number {{orders_placeed.order_number}}</li>
                <li>Phone Number {{orders_placeed.phone_number}}</li>
                
                {% if orders_placeed.delevery_Status.name %}
                <li class="text-danger">Delivery Status : <b>{{orders_placeed.delevery_Status.name}}</b></li>
                {% else %}
                <li class="text-danger">Delivery Status : <b> Order(s) Placeed</b></li>
                {% endif %}
                <li>Paid: {{orders_placeed.paid|yesno:'YES,NO'}}</li>
                <li>Payment Method: {{orders_placeed.payment_method}}</li>
            </ul>
           
            <table class="table">
                
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Name</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>DateTime</th>
                        <th>Total</th>
                    </tr>
                </thead>

                {% for orders_place in orders_placeed.items.all %}


                <tbody>
                    <tr>
                        <td scope="row">
                            <a href="{{orders_place.product.get_absolute_url}}">

                                <img src="{{orders_place.product.image.url}}" style="height: 100px; width: auto;"
                                    alt="{{orders_place.product..name}}">

                            </a>
                        </td>
                        <td scope="row"> {{orders_place.product.name|truncatewords:20}}</td>
                        <td scope="row">{{orders_place.quantity}}</td>
                        <td scope="row">{{orders_place.price}}</td>
                        <td scope="row">{{orders_place.date_add}}</td>
                        <td scope="row">{{orders_place.get_cost}} </td>

                    </tr>

                </tbody>
               
                <!-- <caption class="">GRAND TOTAL {{orders_place.grand_total}}</caption> -->

                {% endfor %}

            </table>
            <hr>
            {% empty %}
             <p> no results found</p>
            {% endfor %}
        </div>
        
        {% if request.user.is_staff and request.GET.q %}
            
       
            
        <div class="col-md-4 col-lg-4 col-xl-4">
            <form action="" method="POST">
                {% csrf_token %}
                
                   
                    {{ form.delevery_Status}}
                    <button id="change_status" class="btn display-block text-center" style="background-color:#3d589e;color: white"
                    type="submit">Change Status</button>
                
            </form>
        </div>
        {% endif %}
    </div>
</div>






{% if request.user.is_staff %}
  <style>
       .header-middle{
        display:None;
    }
    #id_delevery_Status{
       margin-bottom: 5%;
       width: 50%;
    }
#change_status{
    float: right;
}
  </style>
{% endif %}








{% endblock %}

templates/reports/customers.html
{% extends 'header1.html' %}

{% load static %}
{% load humanize %}
{% load thumbnail %}
{% block title %}

Your Shopping Cart
{% endblock %}


{% block content %}

{% if messages %}
{% for message  in  messages %}
 <div id="alert" class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
   </button>
   <strong class="text-center">{{message}}</strong> 
 </div>
 
 <script>
   $(".alert").alert()
   $("#alert").fadeOut(5000);
 </script> 
{% endfor %}
    
{% endif %}
    

<div class="container">
    <form action="{% url 'reports:change_order_status' %}" method="get">
        <div class="input-group text-center" style="justify-content:center">
            <input class="form-control" type="search" name="q" value="{{request.GET.q}}" placeholder="search for order number or code" required>
            <button class="btn btn-search " style="background-color: black;color: white;"
            type="submit">search</button>
        </div>
    </form>
    <div class="row">
        

        <div class="col">

            <a class="btn btn-sm my-4" style="background-color: #3d589e; color: white" href="{% url 'reports:customers' %}">clear
                search</a>
               

            <h3 class="float-right"><span class="btn badge badge-pill badge-primary text-light" style="background-color: #3d589e; color: white" title="{{orders.count|apnumber}} Customers" data-toggle="tooltip">Total {{orders.count}} </span>
              

            </h3>
           
            <form action="" method="get">                  
     
        <table class="table">

            <h3 class="text-center">ALL CUSTOMERS</h3>
            <div class="input-group my-4">
                   
                <input class="form-control" type="date" name="q1" value="{{request.GET.q1}}">
                <input class="form-control" type="date" name="q2" value="{{request.GET.q2}}">
                <button class="btn btn-search " style="background-color: #4654A3;color: white;"
                type="submit">search</button>
            </div>
            <thead>

                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Number Of Orders</th>
                    <th>Number Of Items</th>
                    <th>Date Registered</th>
                    <th>Last Loged In</th>
                    <th>View Orders</th>
                </tr>
            </thead>
            {% for customer_orders in orders %}
            <tbody>
                <tr>
                    <td scope="row">{{forloop.counter}} </td>
                    <td scope="row">{{customer_orders.user__username}}</td>
                    <td scope="row">{{customer_orders.user__email}}</td>
                    <td scope="row">{{customer_orders.orders_total}}</td>
                    <td scope="row">{{customer_orders.purchase}}</td>
                    <td scope="row">{{customer_orders.user__date_joined}}</td>
                    <th class="row">{{customer_orders.user__last_login|timesince}}</th>
                    <td scope="row">
                        <a class="" style="color: #3D589E;"
                            href="{% url 'reports:customers_order' customer_orders.user__id %}">View Orders</a>
                    </td>


                </tr>

            </tbody>
            {% endfor %}
            </form>
        </table>


    </div>
</div>
</div>
</div>

<style>
    .date {
        display: inline;
        margin: 1px
    }
    .header-middle{
        display:None;
    }
    
</style>
{% endblock %}

templates/reports/product_report_detail.html
{% extends 'header1.html' %}
{% load static %}
{% load humanize %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col">
            <a class="btn" style="background-color: #3d589e; color: white" href="{% url 'reports:product_report' %}"> Back</a>
            <span class="btn badge badge-primary float-right display-4" style="background-color: #3d589e; color: white" tooltip="{{product_available.count|apnumber}} available" data-toggle="tooltip">Total {{Product_available.count}}</span>

            <h4 class="text-center capitalize">Products Under  {{name}}


            </h4>


            <table class="table">

                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th>Image</th>
                        <th>Name</th>
                        <th>Quantity</th>
                        <th>Price</th>
                       
                    </tr>
                </thead>

                {% for Products in Product_available %}


                <tbody>
                    <tr>
                        <td scope="row">{{forloop.counter}}</td>
                        <td scope="row">
                            <a href="{{Products.get_absolute_url}}">

                                <img src="{{Products.image.url}}" style="height: 100px; width: auto;"
                                    alt="{{Products..name}}">

                            </a>
                        </td>
                        <td scope="row"> {{Products.name}}</td>
                        <td scope="row">{{Products.quantity}}</td>
                        <td scope="row">{{Products.price}}</td>
                    </tr>

                </tbody>
               
                <!-- <caption class="">GRAND TOTAL {{Products.grand_total}}</caption> -->

                {% empty %}
                <p>no orders placed yet <a href="/">create some  orders now</a></p>
                {% endfor %}
            </table>
           
         
        </div>
    </div>
</div>





<style>
     .header-middle{
        display:None;
    }
</style>


{% endblock %}

templates/reports/products_report.html
{% extends 'header1.html' %}
{% load static %}

{% block content %}


<!-- work on this file :delete this in category_Sales.html
 -->
<style>
  * {
    box-sizing: border-box;
  }

  body {
    margin: 0;
    font-family: Arial, Helvetica, sans-serif;
  }

  /* The grid: Three equal columns that floats next to each other */
  .column {
    float: left;
    width: 33.33%;
    padding: 20px;
    text-align: center;
    font-size: 25px;
    cursor: pointer;
    color: white;
    font-weight: bold;
  }

  .header-middle {
    display: None;
  }

  .containerTab {
    padding: 20px;
    color: white;
  }

  /* Clear floats after the columns */
  .row:after {
    content: "";
    display: table;
    clear: both;
  }

  /* Closable button inside the container tab */
  .closebtn {
    float: right;
    color: white;
    font-size: 35px;
    cursor: pointer;
  }
</style>
</head>

<body>




  <div style="text-align:center">
    <h2 class="display-4"><b> STORE STATISTICS </b></h2>
    <p class="text-muted">Click on each box to display content:</p>
  </div>

  <!-- Three columns -->
  <div class="row">
    <div class="column" onclick="openTab('b1');"  style="background-color: #D7782F;color:white">
      Quantity Available
    </div>
    <div class="column" onclick="openTab('b2');"style="background-color: #270E46; color: white">
      Quantity Sold

    </div>
    <div class="column" onclick="openTab('b3');" style="background-color: #2D589E; color: white">
      Out Of Stock
    </div>

  </div>

  <!-- Full-width columns: (hidden by default) -->
  <div id="b1" class="containerTab" style="display:block;">
    <span onclick="this.parentElement.style.display='block'" class="closebtn">&times;</span>
    <h2 class="display-4 text-center">Current Stock</h2>
    <!-- table -->


    <table class="table table-bordered table-hover">
      <!-- search -->

      <hr>
      <thead class="thead-light ">

        <tr>
          <th scope="col">#</th>
          <th scope="col">Category </th>
          <th scope="col">Available Quanity</th>

          <!-- <th scope="col">Quanity Sold</th> -->
            <th scope="col">View</th>



        </tr>
      </thead>
      {% for items in mostly_bought_products %}
      <tbody>

        <tr class="text-dark">
          <td id="id" class="" scope="row"> {{ forloop.counter}} </td>
          <td scope="row"> {{ items.name }} </td>
          <td scope="row"> {{ items.quantity_available }} </td>
          <!-- <td scope="row"> {{ items.quantity_bought }} </td> -->
            <td scope="row">
              <a  style="background-color: #3d589e; color: white"  class="btn"href="{% url 'reports:products_report_detail' items.name %}">view</a>
            </td>

          
        </tr>

        {% empty %}

        <p class="text-white"> no data</p>
      </tbody>

      {% endfor %}
    </table>


    <!-- table end-->
  </div>

  <div id="b2" class="containerTab" style="display:none;">
    <span onclick="this.parentElement.style.display='none'" class="closebtn">&times;</span>
    <h2 class="display-4 text-center">Items Sold Out</h2>
    <!-- date try here -->



    <table class="table table-bordered table-hover" style="color:black">
      <!-- search -->

      <hr>
      <thead class="">

        <tr>
          <th scope="col">#</th>
          <th scope="col">Category </th>
          <th scope="col">Name</th>
          <th scope="col">View</th>
   

        </tr>
      </thead>
      {% for sold_products in quantity_sold_products %}
      <tbody>

        <tr>
          <td id="id" scope="row"> {{ forloop.counter}} </td>
          <td scope="row"> {{ sold_products.name }} </td>
          <td scope="row"> {{ sold_products.quantity_bought }} </td>

          <td scope="row">
            <a  style="background-color: #3d589e; color: white"  class="btn"href="{% url 'reports:products_remaiaining_detail' sold_products.name %}">view</a>
          </td>



        </tr>

        {% empty %}

        <p class=""> No Data Available</p>
      </tbody>

      {% endfor %}
    </table>

    <!-- table end-->

    <!-- filter table -->
  </div>
    <!-- Full-width columns: (hidden by default) -->
    <div id="b3" class="containerTab" style="display:none;">
      <span onclick="this.parentElement.style.display='none'" class="closebtn">&times;</span>
      <h2 class="display-4 text-center">Out Of Stock </h2> 
      <!-- table -->


      <table class="table table-bordered table-hover" style="color: black;">

          <small class="text-muted">products in negative means a customer(s) have orderd for it but out of stock</small>
        <thead class="">

          <tr>
            <th scope="col">#</th>
            <th scope="col">Category </th>
            <th scope="col">Name</th>
            <th scope="col">Quntity</th>
            
        </thead>
        {% for items in out_of_stock %}
       
        <tbody>

          <tr>
            <td id="id" scope="row">{{ forloop.counter}} </td>
            <td scope="row"> {{ items.category__name }} </td>
            <td scope="row"> {{ items.name }} </td>
            <td class="text-danger" scope="row">{{ items.quantity}}</td>

           
          </tr>

          {% empty %}

          <p class="text-dark"> no data available</p>
        </tbody>

        {% endfor %}
      </table>


      <!-- table end-->
    </div>

    </form>




 




  <script>
    function openTab(tabName) {
      var i, x;
      x = document.getElementsByClassName("containerTab");
      for (i = 0; i < x.length; i++) {
        x[i].style.display = "none";
      }
      document.getElementById(tabName).style.display = "block";
    }
  </script>


  {% endblock %}