cart/urls.py
from django.conf.urls import url
from django.urls import  path
from . import views

app_name = 'cart'

urlpatterns = [
    path('yourcart', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path("cart_size/",views.cart_size, name="cart_size"),

]

orders/urls.py
from django.urls import  path
from . import views

app_name = 'orders'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('checkout_success/',views.checkout_success,name='checkout_success'),
    path('checkout_fail/',views.checkout_fail,name='checkout_fail'),
    path('checkout_payment/<str:order_number>/',views.checkout_payment,name='make_payment'),

    path("orders/",views.orders,name="orders"),
    path('order_items/<str:order_number>/<int:pk>/',views.order_items,name='order_items'),
    path('my_orders/',views.my_order_detail,name='my_order_detail'),

    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # <-- this one here


]

solvergeek/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    # path('ecommerce/',include('ecommerce.urls')),
    path('', include('ecommerce.urls')),
    path('xconnect/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('orders.urls')),
    path('', include('cart.urls')),
    path('', include('reports.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('terms_and_conditions/', TemplateView.as_view(
        template_name='terms_and_conditions.html'), name='termsandconditions'),
    path('return_policy/', TemplateView.as_view(template_name='return_policy.html'),
         name='returnpolicy'),


]#+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
elif getattr(settings, 'FORCE_SERVE_STATIC', False):
    settings.DEBUG = True
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    settings.DEBUG = False

# urlpatterns+=static(settings.MEDIA_ROOT,document_root=settings.MEDIA_ROOT)

# handler404 = 'ecommerce.views.error404'
# handler500 = 'ecommerce.views.error500'

orders/models.py
import datetime

from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import F, Sum
from django.db.models.signals import post_save
from django.dispatch import receiver
from ecommerce.models import Base_Model, Product
from hashids import Hashids
from mapbox_location_field.models import LocationField
# from mapbox_location_field.spatial.models import SpatialLocationField  
from location_field.models.plain import PlainLocationField
# Create your models here.
hashids = Hashids()
from random import randint


class Staff_Email(Base_Model):
    
    name = models.ForeignKey(User,on_delete=models.CASCADE,limit_choices_to={'is_staff': True})
    email = models.EmailField()
    receive_order = models.BooleanField(default=True)
 


    class Meta:
        verbose_name = 'staff Email'
        verbose_name_plural='staff Emails'
    
    def __str__(self):
        return f'{self.name.username,self.email}'

class Region(Base_Model):
    name = models.CharField(max_length=200,unique=True)
    def __str__(self):
        return self.name

    class  Meta:
        ordering = ['name']

class City(Base_Model):
    region=models.ForeignKey(Region,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=200)

  

    def __str__(self):
        return f"{self.name} in {self.region}"
    
    class Meta:
        verbose_name = 'City'
        verbose_name_plural= 'Cities'
        ordering = ['name']


class Delevery_Status(Base_Model):
    name = models.CharField(max_length=600,default='Order Placed')

    class Meta:
        verbose_name = "Delevery Status"
        verbose_name_plural ='Delevery Status'
    
    def __str__(self):
        return self.name


class Pickupstation(Base_Model):
    name = models.CharField(max_length=600)

class Order(Base_Model):
    user =models.ForeignKey(User,on_delete=models.CASCADE,related_name='user')
    name = models.CharField(max_length=8000)
    email = models.EmailField()
    address = models.TextField(null=True)
    phone_number = models.CharField(max_length=15, blank=False)
    delevery_Status = models.ForeignKey(Delevery_Status,on_delete=models.CASCADE,null=True,blank=True)
    # city = models.CharField('City/Closest Landmark',max_length=600)
    
    region =models.ForeignKey(Region,on_delete=models.CASCADE,null=True,blank=True)
    city =models.ForeignKey(City,null=True,on_delete=models.CASCADE,blank=True)
    paid = models.BooleanField(default=False)
    order_number = models.CharField('order number',max_length=500,editable=False)
    location = LocationField(null=True,blank=True)  
    payment_method =models.CharField(max_length=255,null=True,blank=True,editable=False)

    city1 = models.CharField(max_length=255,null=True,blank=True)
    location_google = PlainLocationField(based_fields=['city1'], zoom=7,null=True,blank=True)
    transaction_id =models.CharField(max_length=200,null=True,blank=True)
    pickupstation = models.ForeignKey(Pickupstation,on_delete=models.CASCADE,blank=True,null=True)
    




    class Meta:
        ordering = ('-date_updated', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
    
        return sum(item.get_cost() for item in self.items.all())
    def __str__(self):
        return f'user: {self.user.username} order umber : {self.order_number}'
    
    def gettotal_oders(self):
        # print(len(self.order_number))
        return len(self.order_number)
    




def random_with_N_digits(n):
    range_start = 10**(n-1)
    range_end = (10**n)-1
    return randint(range_start, range_end)

# print (random_with_N_digits(2))

@receiver(post_save,sender=Order)
def create_orders_number(sender,instance,created,*args, **kwargs):
    # now = datetime.datetime.now().strftime("%Y%m%d%H%M")
    if not instance.order_number:
        
        # order_id = hashids.encrypt(instance.id)
        ordernummber= str(random_with_N_digits(8))#+''+str(order_id)
        instance.order_number = ordernummber
        instance.save()

    # print('ordernummber ',ordernummber)



class OrderItem(Base_Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.order.name)

    def get_cost(self):
        if self.price and self.quantity:
            
            return self.price * self.quantity
        else:
            return None


    def grand_total(self):
        return self.get_cost
      



@receiver(post_save,sender=OrderItem)
def subtract_stock(sender,instance,created,*args, **kwargs):
    if created:
        # print('instance signal',instance.product.name,'quantity',instance.quantity)

        products = Product.objects.filter(name=instance.product.name).update(
            quantity=F('quantity')-instance.quantity)
        
    if  instance.product.quantity <=0:
        print('instance signal',instance.product.name,'quantity',instance.product.quantity)

orders/forms.py
from django import forms
from .models import Order,City


class OrderCreateForm(forms.ModelForm):
    address = forms.CharField(required=True,widget=forms.Textarea(attrs={'placeholder':'Street Name / Building /Apartment No /Floor/ Closest Landmark'}))
    class Meta:
        model = Order
        exclude = ['user','paid','city1','location_google','location','delevery_Status','transaction_id','pickupstation']


    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'region' in self.data:
            try:
                region_id = int(self.data.get('region'))
                self.fields['city'].queryset = City.objects.filter(region_id=region_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.region.city_set.order_by('name')

orders/views.py
# from solvergeek.settings import EMAIL_HOST_USER
import datetime

from cart.cart import Cart
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, send_mass_mail
from django.db.models import Count, F, Q
from django.shortcuts import get_object_or_404, redirect, render,HttpResponse
from ecommerce.models import Product
from solvergeek.sendGrid_email import send_sendGredemail
from solvergeek.the_teller_api import make_payment
# from ecommerce.crontab import  python_requests
from django.http import JsonResponse
import  json
from .forms import OrderCreateForm#,City
from .models import Order, OrderItem, Staff_Email,City

# def great():

#     currentTime = datetime.datetime.now()
#     if currentTime.hour < 12:
#         return 'Good Morning'
#     elif 12 <= currentTime.hour < 18:
#         return 'Good afternoon'
#     else:
#         return 'Good Evening'

order_number_=[]
@login_required
def checkout(request):

    form = OrderCreateForm(request.POST or None)
    cart = Cart(request)
    # payment_method ='Online'
    customer_name = ''
    get_total_price =0
    url= ''
    if request.method == 'POST':
        customer_name = request.POST.get('name')
        customer_email = request.POST.get('email')
        customer_address = request.POST.get('address')
        customer_phone_number = request.POST.get('phone_number')
        customer_region = request.POST.get('region')
        customer_city = request.POST.get('city')
        user = request.user
        # order_payment = request.POST['order']
        payment_method = request.POST.get('payment_method')
        get_total_price = cart.get_total_price()

        orders = Order.objects.create(name=customer_name, phone_number=customer_phone_number,\
            user=user,email=customer_email,city_id=customer_city,address=customer_address,region_id=customer_region)

        order_number = orders.order_number
        customer_city =orders.city
        


              
        for item in cart:
            OrderItem.objects.create(
                order=orders,
                product=item['product'],
                price=item['price'],
                quantity=item['quantity'],
            )

        

                # get order email receivers
        order_email_recepients = Staff_Email.objects.values_list(
            'email', flat=True).filter(receive_order=True)

                # send mail to intended staff
        subject_staff = 'Hi'
        message_staff = f'Hello {customer_name} with contact number {customer_phone_number} from {customer_address}  (Google Map link) and close to {customer_city}, having order number {order_number}. \
        \n \t \n He/She prefers to pay {payment_method}. Please confirm, follow up and arrange dispatch. Thank You'

        recepient_staff = order_email_recepients
        email_from = 'Orders@xtayconnectafrica.com'
    

            # send mail to customers
        customer_subject ='Order From XtayconnectAfrica'
        customer_message = f'<strong>Dear Cherished Customer, <br> <br> Your Order has been placed successfully. We will call you soon! <br> <br> Please keep your Order Number <b style="font-size:bold">{order_number}</b> safe and thanks for shopping with us! <br> <br>  To view Your order(s), please click here <a href="https://xtayconnectafrica.com/my_orders/" target="_blank" rel="noopener noreferrer">My Order(s)</a></strong> <br>'
        html_content =customer_message
                
            # send the mail
        try:
            pass

            # send_mail(subject_staff, message_staff, email_from,recepient_staff, fail_silently=False)

                
            # customers
            # send_sendGredemail(customer_email,customer_subject,html_content)

            # cart.clear()           
        except:
            pass

        return JsonResponse({"order_number":order_number})
                    
          
             
        form = OrderCreateForm()
    return render(request, 'order/checkoout.html', {'form': form})

  


def checkout_payment(request,order_number):
    
    if request.method == 'POST':
        payment_method = request.POST.get('payment_method')
        cart = Cart(request)
        order = Order.objects.get(user=request.user,order_number=order_number)


        customer_name = order.name
        customer_email = order.email
        customer_address = order.address
        customer_phone_number = order.phone_number
        customer_region = order.region
        customer_city = order.city
        order_number = order.order_number
    
        amount = cart.get_total_price()
      

        # print(payment_method)
        order.payment_method =payment_method
        order.save()



       

        payment_url_= ''
        if payment_method == 'Online Payment':
            
            make_payment_ = make_payment(customer_email,amount)
           

            payment_url_ =make_payment_.get('payment_url')
            # del request.session['payment_url']
            request.session['payment_url'] = payment_url_
            #token =make_payment_.get('token')
            transaction_id = make_payment_.get('transaction_id')
            order.transaction_id = transaction_id
            order.save()
       

                # get order email receivers
        order_email_recepients = Staff_Email.objects.values_list(
            'email', flat=True).filter(receive_order=True)

                # send mail to intended staff
        subject_staff = 'Hi'
        message_staff = f'Hello {customer_name} with contact number {customer_phone_number} from {customer_address}  (Google Map link) and close to {customer_city}, having order number {order_number}. \
        \n \t \n He/She prefers to pay  {payment_method}. Please confirm, follow up and arrange dispatch. Thank You'

        recepient_staff = order_email_recepients
        email_from = 'Orders@xtayconnectafrica.com'
    

            # send mail to customers
        customer_subject ='Order From Xtayconnect Africa'
        customer_message = f'<strong>Dear Cherished Customer, <br> <br> Your Order has been placed successfully. We will call you soon! <br> <br> Please keep your Order Number <b style="font-size:bold">{order_number}</b> safe and thanks for shopping with us! <br> <br>  To view Your order(s), please click here <a href="https://xtayconnectafrica.com/my_orders/" target="_blank" rel="noopener noreferrer">My Order(s)</a></strong> <br>'
        html_content =customer_message



        try:
            send_mail(subject_staff, message_staff, email_from,recepient_staff, fail_silently=False)

                
            # customers
            send_sendGredemail(customer_email,customer_subject,html_content)

                      
        except:
            pass
        
        cart.clear() 


        payment_url ={
        "payment_url":request.session.get("payment_url")
         }
    
        if payment_method == 'Online Payment':
            return JsonResponse(payment_url,safe=False)
        else: 
            return HttpResponse()



def checkout_success(request):
  
    return render(request, 'order/checkoout_success.html')


def checkout_fail(request):
    return render(request, 'order/checkout_fail.html')


@login_required
def orders(request):
    order_items = Order.objects.all()
    q = request.GET.get('q')
    if q:
        order_items = order_items.filter(
            Q(name__icontains=q) | Q(order_number__icontains=q))

    # print(order_items)
    context = {
        'order_items': order_items,
    }
    return render(request, 'order/order.html', context)


@login_required
def order_items(request, order_number, pk):
    orders = get_object_or_404(Order, order_number=order_number, pk=pk)

    # order_item = orders.items.all()
    # for x in order_item:

    #     print(order_item)

    context = {
        'orders': orders,
        # 'order_items':order_items,
    }
    return render(request, 'order/orderitems.html', context)


@login_required
def my_order_detail(request):
    orders = Order.objects.filter(user=request.user)
    order_size= orders.aggregate(orders_size=Count('items'))

    context = {
        'orders': orders,
        'order_size':order_size,
    }

    return render(request, 'order/my_order_details.html', context)


def load_cities(request):
    region_id = request.GET.get('region')
    cities = City.objects.filter(region_id=region_id).order_by('name')
    return render(request, 'order/city_dropdown_list_options.html', {'cities': cities})

templates/order/checkoout.html
{% extends 'header1.html' %}


{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

<head>
    {% block head %}


    <title>

        {% block title %}
        Your Shopping Cart| Checkout
        {% endblock title %}
    </title>

    {% endblock head %}


</head>

{% block content %}

<!-- {% if messages %}

{% for message in messages %}
<div class="alert alert-{{message.tags}}" role="alert">
    {{message|safe}} <a href="/">Continue Shopping</a>
</div>

{% endfor %}

{% endif %} -->

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-9 col-lg-8">
          

            <form method="post" id="checkoutForm" data-cities-url="{% url 'orders:ajax_load_cities' %}" novalidate>
                {% csrf_token %}
              
<div class="container">
    <div class="row justify-content- center">

      
        <div class="col" id="checkout">
            <div class="section-title">
                <h4 class="title">Checkout</h4>
               
            </div>
            
           <div class="card border-primary" style="background-color: whitesmoke;">
             <div class="card-body bg-muted">
              
               
               <h4> PERSON INFORMATION</h4>
                <div class="form-row">
                   
                  <div class="form-group col-md-4 mb-0">
                    
                    {{ form.name|as_crispy_field }}
                  </div>
                  <div class="form-group col-md-4 mb-0">
                    {{ form.email|as_crispy_field }}
                  </div>
                  <div class="form-group col-md-4 mb-0">
                    {{ form.phone_number|as_crispy_field }}
                  </div>
                </div>
               
                    <h4>ADDRESS / LOCATION</h4> </h4>
                <div class="form-row">
                    <div class="form-group col-md-4 mb-0">
                        {{ form.region|as_crispy_field }}
                      </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.city|as_crispy_field }}
                      </div>
                    
                  
                  </div>


                  <div class="form-row">
                    
                      <div class="form-group col-md-6 mb-0">
                        {{ form.address|as_crispy_field }}
                      </div>
                  
                  </div>

                  {% if cart.get_total_price < 1 %} <p class="text-danger  btn" style="color: 3D589E;">Your Cart Is Empty
                </p>
                <a class="btn mx-6" style="background-color:#3D589E;color: white;" href="/">Continue Shopping</a>

                {% else %}
                

<p class="section-title text-capitalize text-capitalize">By clicking on <b>Order Now,</b> you have agreed to our <b><a style="color: #4654A3" href="{% url 'termsandconditions' %}">terms and conditions</a></b></p>

                    <input  id="save_checkout" type="submit" class="btn btn-primary mb-4" value="Order Now"
                    style="background-color: #3D589E;color: white">
                    

   
       
     
    {% endif %}                  
              </form>
             </div>
           </div>
          </div>
        </div>
    </div>
</div>
    </form>
    
    <div class="col-md-9" id="payment">
        
<div class="card">
    <div class="card-body">
     
            <div class="section-title">
                <h4 class="title">Payment Method</h4>   
            </div>
            <!-- <p class="text-muted">please select a payment method</p> -->

           <form action="#" method="post" id="paymentForm">
            {% csrf_token %}
            <div class="form-row justify-content-center">
             
                <div class="form-group col-md-4  col-sm-4">
             
                <div class="text-center" >
                    <label class="btn text-center" id="payment_method1" style="background-color:#FA7A62;color: white">On line</label>
                </div> 

            </div>
            <div class="form-group col-md-4 col-sm-4">

                <div class="text-center" >
                    <label class="btn text-center" id="payment_method2"  style="background-color: #FA7A62;color: white;">On Delivery</label>
                </div>
                
            </div>

            

        </div> <hr>
        <p class="text-center" id="please_wait"></p>
        <input  type="submit" class="btn" value="Submit order" id="Submit_order" style="background-color:#3D589E;color: white">
           </form>
    </div>
</div>
    </div>

            <div class="col-md-3 my-4">
                <div class="section-title">
                    <h4 class="title">Order(s) Review</h4>
                   
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                    <li class="list-group-item">
                        {{ item.quantity|apnumber }}({{item.quantity }}) {{ item.product.name }}
                        <span id="total_price"> Total GH₵: {{ item.total_price|intcomma }}</span>
                    </li>

                    {% empty %}
                    <p>empty place some orders <a href="/">here</a> </p>
                    {% endfor %}
                    <li class="list-group-item active" style="background-color:#3D589E;color: white">Total Cost: GH₵: {{cart.get_total_price|intcomma }}</li>
                </ul>
            </div>
          
        
   
    </div>
</div>


<!-- <button onclick="getLocation()">Try It</button> -->


<style>
  @media screen and (max-width: 600px){
      #id_address{
        max-width :100%;
      
      }
  }
</style>




{% if user.is_authenticated %}
<script>







    document.getElementById('id_name').value = "{{ request.user.username }}"
    document.getElementById('id_email').value = "{{request.user.email}}"
    document.getElementById('id_phone_number').value = "{{request.user.user.phone_number}}"

    // document.getElementById('id_').value = "{{request.user.phone}}"
    // document.getElementById('total').value=  document.getElementById('total_price').value
</script>

{% endif %}



<script src="{% static 'js/pages/checkout.js' %}"></script>
{% endblock %}

<!-- 

templates/order/checkoout_success.html
{% extends 'header1.html' %}

{% load static %}

<head>

    {% block head %}

    <title>

        {% block title %}
        Your Shopping Cart| Thank you
        {% endblock %}
    </title>

    {% endblock head %}

</head>
{% block content %}
<div class="container">
    <div class="row justify-content-center">
            <div class="col">
                <h1 class="text-center">Thank You For Shopping With Us</h1> <br> <br>

                <h4 class="text-center">Your order has been successfully completed </h4>  <br>

              <ul class="text-center">
                  <li style="display: inline">
                    <a class="btn btn-lg mx-4" style="background-color: #4654A3;color: white;margin-bottom: 10px" href="{% url 'orders:my_order_detail' %}">View Orders</a>

                    <a class="btn btn-lg mx-4" style="background-color: #4654A3;color: white;margin-bottom: 10px" href="/">Continue
                        Shopping</a>
                  </li>
              </ul>
            </div>
       
        
      
    </div>
   

</div>


<script>
    // window.onbeforeunload = function() { return "Your work will be lost."; };
</script>
{% endblock %}

templates/order/checkout_fail.html
{% extends 'header1.html' %}

{% load static %}

<head>

    {% block head %}

    <title>

        {% block title %}
        Your Shopping Cart| Thank you
        {% endblock %}
    </title>

    {% endblock head %}

</head>
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-md-offset-2">
            <h1 class="page-header">Thank You For Shopping With Us
            </h1>
            <h2>But Unfortunately your payment have failed or you canceled the payment transaction
                if its a failure then we appologize and please feel to contact customers support on
                 <strong class="text-info"><a class="btn" href="tel:++233206494929">+233206494929</a></strong> we waiting on your call
               <code class="text-center">Thank you</code> </h2>

    <ul id="reachus"> 
            <li class="li">
                <a class="btn btn-lg" href="/">continue shopping</a>
            </li>
            <li class="li">
                <a class="btn btn-lg"href="{% url 'orders:checkout' %}">Try Again</a>
            </li>
    </ul>
        </div>

       
    </div>
    
</div>
<style>
    .li,.btn{
        display: inline;
        color:#270E46
    }
    #reachus{
        text-align: center;
      
    }
</style>
{% endblock %}

templates/order/city_dropdown_list_options.html
<option value="">Select City/Capital</option>
{% for cities in cities %}
<option value="{{ cities.pk }}">{{ cities.name }}</option>
{% endfor %}

templates/order/order.html
{% extends 'header1.html' %}



{% load static %}

{% block content %}
<nav class="breadcrumb" style="margin-left:68%;font-size: larger;">

  <a style="background-color: #270949;color: white;" title="items bought"  data-toggle="tooltip" class="breadcrumb-item btn" href="{% url 'orders:orders' %}">Orders</a>

      <a style="background-color: #270949;color: white;" title="go home" data-toggle="tooltip" class="breadcrumb-item btn" href="/">Home</a>

</nav>
<div class="container">

    <h4 class="text-center display-4" style="font-weight: bolder;">ITEMS PURCHASED</h4>
    <div class="row">
        <div class="col">
            <section>
                <form action="#" method="GET">
                  <!-- <table class="table  table-sm"> -->
                  <table class="table table-bordered table-hover ">
                    <!-- search -->
                    <input class="my-3" type="text" name="q" id="" placeholder="search" value="{{ request.GET.q }}">
                    <button type="submit">search</button>
                    <hr>
                    <thead class="thead-light">
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Phone</th>
                        <th  scope="col">Email</th>
                        <th scope="col">Order Number</th>
                        <th scope="col">Paid</th>
                        <th scope="col">Date Issued</th>
                        <th scope="col">View</th>
                       
                      </tr>
                    </thead>
                    {% for orders in order_items %}
                    <tbody>
        
                      <tr style="font-size: x-large;">
                        <td id="id" scope="row"> {{forloop.counter}} </td>
                        <td scope="row"> {{ orders.name }} </td>
                        <td scope="row"> {{ orders.phone_number }} </td>
                        <td scope="row"> {{ orders.email }} </td>
                        <td scope="row"> {{ orders.order_number }} </td>
                        <td scope="row"> {{ orders.paid|yesno:'YES,NO' }} </td>

                        <td scope="row"> {{ orders.date_add }} </td>
                          <td scope="row"><a class="text-info btn" href="{% url 'orders:order_items' orders.order_number orders.pk %}">View</a></td>
                           
                      </tr>
                      {% empty %}
        
                      <p class="text-info"> Nothing to show currently</p>
                    </tbody>
        
                    {% endfor %}
                  </table>
                </form>
              </section>
        </div>
    </div>
</div>


{% endblock %}